const Footer = `<div class="container">
<div class="Profile-Service container ">
    <div class="row profile-service d-flex justify-content-center align-items-center text-center">
        <div class="col">
            <img src="images/Image 34.png" alt="">
            <h5>100% secure payments</h5>
            <p>Turpis Eleifend Malesauda Magna</p>
            <p>Congue Domas Id Ullamcorper Neque</p>
        </div>
        <div class="col">
            <img src="images/Image 35.png" alt="">
            <h5>Trustpay</h5>
            <p>Turpis Eleifend Malesauda Magna</p>
            <p>Congue Domas Id Ullamcorper Neque</p>
        </div>
        <div class="col">
            <img src="images/Image 36.png" alt="">
            <h5>Help center</h5>
            <p>Turpis Eleifend Malesauda Magna</p>
            <p>Congue Domas Id Ullamcorper Neque</p>
        </div>
        <div class="col">
            <img src="images/Image 37.png" alt="">
            <h5>shop on the go</h5>
            <p>Turpis Eleifend Malesauda Magna</p>
            <p>Congue Domas Id Ullamcorper Neque</p>
        </div>
    </div>
</div>
</div>

<!-- ********************* MY PROFILE FOOTER SERVICES *****************  -->
<div class="container text-left">
<div class="profile-service-list container">
    <div class="row profile-service-list-content">
        <div class="col">
            <h6>policy-info</h6>
            <ul>
                <li><a href="">Phonepe</a></li>
                <li><a href="">term of site</a></li>
                <li><a href="">term of use</a></li>
                <li><a href="">report abuse & takedown policy</a></li>
            </ul>
        </div>
        <div class="col">
            <h6>company</h6>
            <ul>
                <li><a href="">about us</a></li>
                <li><a href="">core value</a></li>
                <li><a href="">careers</a></li>
                <li><a href="">blog</a></li>
                <li><a href="">sitemap</a></li>
            </ul>
        </div>
        <div class="col">
            <h6>snapdeal business</h6>
            <ul>
                <li><a href="">shopping app</a></li>
                <li><a href="">sell on snapdeal</a></li>
                <li><a href="">advertise on snapdeal</a></li>
                <li><a href="">media enquries</a></li>
                <li><a href="">be a affiliate</a></li>
            </ul>
        </div>
        <div class="col">
            <h6>need help ?</h6>
            <ul>
                <li><a href="">faq</a></li>
                <li><a href="">contact us</a></li>
                <li><a href="">online shopping</a></li>
            </ul>
        </div>
        <div class="col">
            <h6>subscribe</h6>
            <ul>
                <div class="d-flex ">
                    <input type="email" placeholder="Enter Your Email" class="text-center">
                    <button type="submit">Subscribe</button>
                </div>
                <li><a href="">contact us</a></li>
                <li><a href="">online shopping</a></li>
            </ul>
        </div>
    </div>
</div>
</div>
<hr>

<!-- ********************* MY PROFILE FOOTER *****************  -->
<div class="container">
<div class="profile-footer">
    <div class="row">
        <div class="col-9">
            <h6>PAYMENT</h6>
            <div class="profile-footer-image">
                <img src="images/Image 38.png" alt="">
                <img src="images/Image 39.png" alt="">
                <img src="images/Image 40.png" alt="">
                <img src="images/Image 41.png" alt="">
                <img src="images/Image 42.png" alt="">
                <img src="images/Image 43.png" alt="">

            </div>
        </div>
        <div class="col-3">
            <h6>CONNECT</h6>
            <div class="profile-footer-icons">
                <a href=""><img src="images/Image 44.png" alt=""></a>
                <a href=""><img src="images/Image 45.png" alt=""></a>
                <a href=""><img src="images/Image 46.png" alt=""></a>
                <a href=""><img src="images/Image 47.png" alt=""></a>
            </div>
        </div>
    </div>
</div>
</div>`;

document.getElementById('FOOTER').innerHTML = Footer;